/**
 * Taglines — shown in the header on desktop. Keep them under 60 chars.
 * Generated as a single batch; mix of dry and warm humor.
 */

export const TAGLINES: string[] = [
  "Because 3pm somewhere is 4am elsewhere.",
  "DST: the two-week-a-year rage generator.",
  "Now with 100% fewer mental gymnastics.",
  "Meetings, deconfused.",
  "Time travel, minus the paradoxes.",
  "Houston, we have a scheduling problem.",
  "Yes, I checked twice. You should too.",
  "The planet keeps spinning. We keep coping.",
  "For people with too many Slack statuses.",
  "No meeting should start at 2am.",
  "Probably safer than a spreadsheet.",
  "Not a doctor of time, but close.",
  "A grid of hours. Very exciting.",
  "Your circadian rhythm called.",
  "Built for the 'wait, whose Monday?' era.",
  "Pencil it in. Across three continents.",
  "Finally, an overlap that isn't 3am.",
  "Because 'let me check' is not a schedule.",
  "A calendar that respects sleep.",
  "Time zones: now slightly less hostile.",
  "The grid knows. Trust the grid.",
  "No one should meet at 4am willingly.",
  "Zone out less, zone in more.",
  "Planet Earth: a timezone stew.",
  "Daylight saving? We'll warn you.",
  "Nothing rhymes with UTC.",
  "Minutes, hours, existential dread.",
  "The cheapest time machine available.",
  "Greenwich had a good run.",
  "Midnight is a lifestyle choice.",
  "Meet me at any of these hours.",
  "Also works in space, probably.",
  "The sun rises somewhere. Find out where.",
  "From IANA with love.",
  "Clocks: they tick. Weird, right?",
  "Your home zone is highlighted for a reason.",
  "One grid to rule them all.",
  "2 PM in Paris is a whole different vibe.",
  "Small tool. Big time energy.",
  "Calendar rage, canceled.",
  "Better than asking everyone to DM.",
  "Finally, proof that 7am is too early.",
  "Because Slack huddles don't fix this.",
  "We love a good overlap.",
  "The antidote to 'what time works?'",
  "Time zones: sorted.",
  "Everything's clearer in landscape mode.",
  "The most respected column on Earth.",
  "Color-coded for your convenience.",
  "Not affiliated with any actual wizards.",
  "Plan like a diplomat.",
  "Timekeeping, meet usability.",
  "The little app that respects your sleep.",
  "Fewer 2am calls, statistically.",
  "Because time is the only currency.",
  "World clock, upgraded.",
  "A schedule that doesn't hurt.",
  "Meetings should not require math.",
  "For the globally distributed team.",
  "Hours are friends, not enemies.",
  "Also works on your phone, weirdly.",
  "Because 'find a time' is a full job.",
  "Not open source. Not a startup. Just helpful.",
  "Keeping you out of 4am meetings since 2026.",
  "The world does not revolve around UTC.",
  "Plan it. Print it. Sleep well.",
  "Now with slightly better abbreviations.",
  "A calm place in the universe.",
  "Built for the people who care about 'when'.",
  "DST transitions flagged. You're welcome.",
  "Put the grid on the fridge.",
  "Your project manager will thank you.",
  "It's 5 o'clock somewhere. Is it here?",
  "The cure for 'wait, is that AM or PM?'",
  "Plan meetings like you plan holidays.",
  "Less timezone math. More life.",
  "Feat. the zones you actually care about.",
  "Wake up earlier. Or don't.",
  "Shift happens. We're ready.",
  "More color than your calendar deserves.",
  "Keeping it clean. And correct.",
  "Your overlap window, visualized.",
  "Designed for humans, not servers.",
  "A small act of global empathy.",
  "Because the weekend is different there.",
  "The only app that likes Sundays.",
  "Skip the jet lag math.",
  "Tables beat mental gymnastics.",
  "Made for afternoons in Jakarta.",
  "Designed late at night. Obviously.",
  "The zone you're in is fine. Really.",
  "No fine print. Just grid lines.",
  "Be kind to your 8am self.",
  "Print it. Pin it. Attend it.",
  "Also great for parents of teens.",
  "Avoid the 11pm Tuesday trap.",
  "Saved from the 'reschedule' loop.",
  "The overlap window is right there.",
  "Scrum masters welcome.",
  "Schedule peacefully.",
  "For the distributed, not the distracted.",
];

export function randomTagline(): string {
  return TAGLINES[Math.floor(Math.random() * TAGLINES.length)];
}
